### ISSUE TITLE
[NetHook2]: Unable to hook CWebSocketConnection::BBuildAndAsyncSendFrame: func scan failed.

### ISSUE THREAD

**Issue by wangxingzhen** [SteamRE/SteamKit#1368] opened 2024-06-24 12:25 UTC
### What did you expect to happen?

Run successfully

### Instead of that, what actually happened?

I according to the readme file (https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) run NetHook2. DLL on my windows11 computer, Error: {Unable to hook CWebSocketConnection: : BBuildAndAsyncSendFrame: func scan failed.}
I used NetHookAnalyzer2 to look at the generated file and found that there was only in direction and no out direction.
_If instead you see a failure message or your Steam process crashes, it's possible that an update to Steam may have broken one of NetHook2's binary signature scans and they will require updating. If you're on the beta branch of Steam, try using the non-beta version and vice versa._
Yes, I've tried

### Relevant log output

```plain
Initializing NetHook2...
Built at 2024-05-28 06:54:51 +00:00 from 4ab90ab (2024-05-28 16:53:14 +1000)
CCrypto::SymmetricEncryptChosenIV = 0x6CF6DF00
PchMsgNameFromEMsg = 0x6CF7F8F0
Detoured SymmetricEncryptChosenIV!
CWebSocketConnection::BBuildAndAsyncSendFrame = 0x00000000
CCMInterface::RecvPkt = 0x6C911710
Unable to hook CWebSocketConnection::BBuildAndAsyncSendFrame: func scan failed.
Detoured CCMInterface::RecvPkt!
```

### Additional Information

![332875d0ebd5cae642dba50f15fa6e46](https://github.com/SteamRE/SteamKit/assets/44692411/338dc9f5-44c4-469d-bfe5-478dcb31f87b)

**Comment by wangxingzhen** [comment] 2024-06-24 12:37
my steam client version is 1718904662

**Comment by xPaw** [comment] 2024-06-24 12:49
Duplicate of #1366?

**Comment by wangxingzhen** [comment] 2024-06-24 13:02
> Duplicate of #1366?

The error is different, I thought it was a different error, sorry, I will close this issue and wait for pr

**Closed** 2024-06-24 13:03 UTC
Labels: bug
