### ISSUE TITLE
Problem with WPF-application

### ISSUE THREAD

**Issue by Kapranov98** [SteamRE/SteamKit#360] opened 2017-01-31 11:09 UTC
Hey. I'm trying to create an application on WPF. I can not deal with the login page. The application hangs at the loop, shown below. Methods (OnConnected, OnDisconnected, OnLoggedOn, OnLoggedOff) are not called. Can you give an example of implementation in WPF?

`while (isRunning)
            {
                manager.RunWaitCallbacks(TimeSpan.FromSeconds(1));
            }`

**Comment by stil** [comment] 2017-01-31 13:51
It's not an issue with SteamKit and I don't think this question belongs here. You need to run the loop on separate thread so it won't block the UI.

```csharp
Task.Run(() => { while (isRunning) { manager.RunWaitCallbacks(TimeSpan.FromSeconds(1)); } });
```
And you need to be very careful when you're accessing UI from callback methods (those you mentioned, OnConnected, OnDisconnected, OnLoggedOn, OnLoggedOff). Make sure you access UI exclusively from UI thread. In WPF you can do it with `Dispatcher.Invoke` method.

If you modify UI from loop thread instead of UI thread your application will instantly crash. Good luck.

**Comment by VoiDeD** [comment] 2017-02-03 16:14
I'm not super familiar with WPF, but perhaps `DispatcherTimer` may be better than a full blown thread. that way if you poll callbacks within your dispatcher/UI thread (if my understanding of this is correct), then you won't need to invoke every single action--you'll already be on the UI thread.

**Comment by jurzer** [comment] 2017-02-07 21:29
I think the problem is the same that I have https://github.com/SteamRE/SteamKit/issues/358. I have the same in WPF application, nothing happens, despite the fact that in console everything works. And as I already wrote in your question that's the problem in this code

```c#
endPointTask.ContinueWith(t =>
{
    if (t.IsFaulted || t.IsCanceled)
    {
        if (t.Exception != null)
        {
            foreach (var ex in t.Exception.Flatten().InnerExceptions)
            {
                DebugLog.WriteLine("TcpConnection", "Endpoint task threw exception: {0}", ex);
            }
        }

        Release(userRequestedDisconnect: false);
        return;
    }

    destination = t.Result;
    Console.WriteLine(destination);

    if (destination != null)
    {
        DebugLog.WriteLine("TcpConnection", "Connecting to {0}...", destination);
        TryConnect(timeout);
    }
    else
    {
        DebugLog.WriteLine("TcpConnection", "No destination supplied from endpoint task");
        Release(userRequestedDisconnect: false);
        return;
    }

}, TaskContinuationOptions.LongRunning);
```
It's part of the Connect function of class TcpConnection. endPointTask.ContinueWith is called and it returns nothing, hence the crash. If the destination specify the ip without calling endPointTask.ContinueWith and call TryConnect(), then everything works. That is, if instead of the above code to write e.g. 
```c#
destination = new IPEndPoint(IPAddress.Parse("155.133.242.9"),27019);
TryConnect(timeout);
 ```
then it will work.

Sorry for my English.

**Comment by JustArchi** [comment] 2017-02-07 21:46
I'm not sure if it's a good idea to run main callback manager loop on UI thread, since ```RunWaitCallbacks()``` is synchronous, and it might be observable degradation with many callbacks waiting in the queue, even if everything else properly uses async/await to free the thread from excessive work.

"Syncing" with GUI thread for GUI updates and running main loop in the backgrounds sounds much better to me, as there will always be callbacks that we simply ignore, yet have to process regardless.

I'd need to check it myself for something backing up my theory, but based on what SK2 is doing I'm not sure if UI thread is the right place for looking callback manager loop, even if it's trying to be async where possible. It'd probably be wanted to rewrite entire managed to support async and make it possible for user to ```await```  ```RunCallbacks()``` instead.

**Comment by VoiDeD** [comment] 2017-02-08 01:26
I don't see any immediate issues with using `RunCallbacks` (or in the UI thread as long as the callback handlers aren't doing any heavy processing.

**Comment by Netshroud** [comment] 2017-06-25 01:38
Closing as answered.

**Closed by Netshroud** 2017-06-25 01:38 UTC
Labels: question

**Comment by MrBrax** [comment] 2018-02-08 14:06
I just can't get this to work, it's extremely confusing doing cross-thread stuff.

Why doesn't it run the callbacks in the background automatically? This is a very weird library.
