### ISSUE TITLE
Nethook2 Dumping null messages after 12.02.20 update

### ISSUE THREAD

**Issue by nikindreus** [SteamRE/SteamKit#815] opened 2020-02-12 10:38 UTC
![image](https://user-images.githubusercontent.com/47863887/74327220-d1e67600-4d9c-11ea-857b-4f70d53f3d46.png)

**Comment by yaakov-h** [comment] 2020-02-12 10:41
That looks like a null message name, not null data.

See #804.

**Comment by dasyah** [comment] 2020-02-14 05:18
any chance this will fixed?

**Comment by AmiT177** [comment] 2020-02-16 16:43
> 
> 
> any chance this will fixed?

You can compile the DLL from PR #804 which has a workaround for it

**Comment by dasyah** [comment] 2020-02-17 04:23
> 
> 
> > any chance this will fixed?
> 
> You can compile the DLL from PR #804 which has a workaround for it

I compile that,but I cant inject it, I use exstream injector I get error System.Exception: The Injection method used returned NULL , then I use another injector like GameOwner,didnt found any error but,I dint think its work,I only get message : 

`CCrypto::SymmetricEncryptChosenIV = 0x6e44bd60
pGetMessageList = 0x6e3a6d9d
pInfos = 0x6e96e870
numMessages = 121979199`

NOthing else,even I open csgo nothink changed on console/neethook analyzer

**Comment by azuisleet** [comment] 2020-02-17 04:35
NetHook is self-injecting, as documented in the readme: `rundll32 "<Path To NetHook2.dll>",Inject`

From the output it doesn't look like numMessages is correct, so that patch may be out of date.

**Comment by AmiT177** [comment] 2020-02-17 05:43
In that case, they might have changed somethings in the latest update again.
There's a very dirty workaround, for now, you can change the `(null)` part of the file name to a random type, ex `k_EMsgGCSystemMessage` and that would make NetHook Analyzer usable again.

**Comment by m4dEngi** [comment] 2020-02-17 07:02
... or use steamclients built-in name lookup function.

**Comment by AmiT177** [comment] 2020-02-17 19:31
didn't even see that PR

**Comment by xPaw** [comment] 2020-05-16 09:48
This is a duplicate of #763

**Comment by yaakov-h** [comment] 2020-05-16 11:01
Fixed by #765.

**Closed by yaakov-h** 2020-05-16 11:01 UTC
