### ISSUE TITLE
nethookanalyzer2 infrequent System.IO.IOException when inside folder nethook2 is currently writing to

### ISSUE THREAD

**Issue by 2c2c** [SteamRE/SteamKit#127] opened 2015-06-20 01:20 UTC
Using the two together real-time seems to work fine aside from the exception popup coming up a couple times per minute.

```

************** Exception Text **************
System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Steam\nethook\1434759903\1212_in_5453_k_EMsgClientFromGC.bin' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at System.IO.File.ReadAllBytes(String path)
   at NetHookAnalyzer2.NetHookItem.ReadAsProtobufMsg[T]() in f:\steamkit\SteamKit\Resources\NetHookAnalyzer2\NetHookAnalyzer2\NetHookItem.cs:line 132
   at NetHookAnalyzer2.NetHookItem.ReadInnerMessageName() in f:\steamkit\SteamKit\Resources\NetHookAnalyzer2\NetHookAnalyzer2\NetHookItem.cs:line 86
   at NetHookAnalyzer2.NetHookItem.get_InnerMessageName() in f:\steamkit\SteamKit\Resources\NetHookAnalyzer2\NetHookAnalyzer2\NetHookItem.cs:line 30
   at NetHookAnalyzer2.NetHookItemExtensions.AsListViewItem(NetHookItem item) in f:\steamkit\SteamKit\Resources\NetHookAnalyzer2\NetHookAnalyzer2\NetHookItemExtensions.cs:line 30
   at NetHookAnalyzer2.MainForm.OnFolderWatcherCreated(Object sender, FileSystemEventArgs e) in f:\steamkit\SteamKit\Resources\NetHookAnalyzer2\NetHookAnalyzer2\MainForm.cs:line 242


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
NetHookAnalyzer2
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///F:/steamkit/SteamKit/Resources/NetHookAnalyzer2/NetHookAnalyzer2/bin/Debug/NetHookAnalyzer2.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SteamKit2
    Assembly Version: 1.6.2.38243
    Win32 Version: 1.6.2.38243
    CodeBase: file:///F:/steamkit/SteamKit/Resources/NetHookAnalyzer2/NetHookAnalyzer2/bin/Debug/SteamKit2.DLL
----------------------------------------
protobuf-net
    Assembly Version: 2.0.0.668
    Win32 Version: 2.0.0.668
    CodeBase: file:///F:/steamkit/SteamKit/Resources/NetHookAnalyzer2/NetHookAnalyzer2/bin/Debug/protobuf-net.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.57.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

```

**Comment by Netshroud** [comment] 2015-06-20 08:35
I couldn't reproduce on my machine, but this should be fixed by fe0ca3f.

**Comment by 2c2c** [comment] 2015-06-22 00:20
This fixed it. I'm in an unusual case of having nethook/nethookanalyzer on a HD with the steam folder being on my SSD, so I guess that may have exacerbated the issue

**Comment by Netshroud** [comment] 2015-06-22 07:28
That makes me even more confused, as that matches my setup. :confused:

**Closed by Netshroud** 2015-06-22 07:28 UTC
Labels: bug

**Comment by Nacorpio** [comment] 2015-06-24 04:16
I found that when I launched a game, the NetHook2 analyzer crashed. I don't remember if it was with that exception, but it certainly did crash.

**Comment by Netshroud** [comment] 2015-06-24 07:30
Do you have the stack trace? If you don't have it recorded, it should still be in the Windows Event Log from the time of the crash.

**Comment by Nacorpio** [comment] 2015-06-24 12:58
I have been trying to reproduce the crash with no luck whatsoever.
No idea what was going on before.
