### ISSUE TITLE
nethook2 dll (time out)

### ISSUE THREAD

**Issue by alainhb2000** [SteamRE/SteamKit#365] opened 2017-02-14 14:02 UTC
Hi, i'm having issues with nethook2 dll, i'm getting a timeout error, when trying to hook dota2 process, and then it crashes.

Some recomendations?

**Comment by psychonic** [comment] 2017-02-14 14:19
Hook the steam process instead of the Dota process, and also confirm
that no errors are displayed at the start of the Nethook console window.

-- 
Nicholas Hastings

**Comment by alainhb2000** [comment] 2017-02-14 14:32
No, it only gives the timeout with the dota process, with the steam client works fine.

**Comment by alainhb2000** [comment] 2017-02-14 15:02
when you host your own local game, dota creates and independent connection to steam, with an anonymous server.

**Comment by psychonic** [comment] 2017-02-14 15:05
> No, it only gives the timeout with the dota process, with the steam client works fine.

It wasn't a yes or no question., or a question at all. I was saying to hook the steam process as that's where the detoured functions are. You will see both Steam messages as well as Dota GC messages dumped.

The only case where you would need to hook the dota process directly is if you were running a standalone, dedicated server, without the Steam client running.

**Comment by alainhb2000** [comment] 2017-02-14 17:45
Sorry for the missunderstanding.
I confirm to you, that hook the steam process is working fine. 

What i'm doing, is hooking the steam client comunication, and so the dota 2 separate communication, this connection is made when you launch your local lan lobby, dota 2 creates a anonymous dedicated server, that connects to steam using another connection, not trough steam client.

The thing is that with previous versions of nethook this thinks worked fine. With this version is not working, at least for me.

And i'm not using a dedicated server, as far as you know dota 2 reborn doesn't allow dedicated servers.

If you want i can give you more details privately.

**Comment by alainhb2000** [comment] 2017-02-14 18:16
Do you know any s-t-e-a-m server emulators? think in people who doesn't have internet all the time. :)
Please tell me if the hooking timeout could have a solution. 
![sin titulo](https://cloud.githubusercontent.com/assets/16402933/22942519/d5ef15c4-f2b7-11e6-8e33-18544562f7af.png)

**Comment by psychonic** [comment] 2017-02-14 18:19
All of my stuff uses Steam and the Dota GC. I just block or fake a few of the outgoing and incoming messages, and the lobby object itself on the server side.

**Comment by alainhb2000** [comment] 2017-02-14 18:26
I sent you an email some time ago, I was using an alpha version of your mod dll, and I managed to connect to a dedicated server with the emulator coordinator, but it does not load the game mode, just use a rare all pick mode, even sending the correct lobby cache.

**Comment by psychonic** [comment] 2017-02-14 18:48
Yes, I ignored the email as I was annoyed at the time that you were asking for help with a leaked or stolen copy of the plugin. It was defaulting to the old All Pick mode (before it was reworked for ranked, and later also unranked), and you were lacking the documentation to set a different one.

I will try to troubleshoot the nethook issue later today when able.

**Comment by alainhb2000** [comment] 2017-02-14 19:27
Jajja leaked or stolen, no. Downloaded from here (Github) S2 branch.
Thanks for your help. And by the way, theres any change that you could share your new mod dll version.

**Comment by psychonic** [comment] 2017-02-14 19:37
What's on Github now is only enough to allow the server to run at all on Windows - (it's fine as-is on Linux), and to be able to load plugins. It does not have any of the lobby injection or other logic. That was in a separate plugin. I misunderstand if you were using your own emulator to power that piece.

I do plan to eventually share what I have in some form. It just needs to be cleaned up and some things ripped out. It hasn't been a priority.

**Comment by alainhb2000** [comment] 2017-02-14 19:51
Well, actually my emulator only works with local lobbies (hosted on my own pc), i've tested with that mod dll, and noticed that when i send on the lobby cache with the lan property set to false, to simulate a server hosted on steam network, the dedicated server process gets closed. The tricks i've done is to send the lobby cache with the lan property on true to the server, and lan set to false to clients, and cycling the dedicated server port on each new process. But as i previously mentioned, the match only starts in all pick mode.

**Comment by psychonic** [comment] 2017-02-16 01:19
I am able to load nethook into both Steam and Dota 2 (32-bit) without issue. I do also see what you mean about some messages only going through Dota's copy of it when starting a listen server.

`rundll32 NetHook2.dll,Inject`
`rundll32 NetHook2.dll,Inject dota2.exe`

[](https://i.imgur.com/mVC8EFc.png)

**Comment by psychonic** [comment] 2017-02-16 01:33
> I do also see what you mean about some messages only going through Dota's copy of it when starting a listen server.

I can explain this now as well.

For the Steam (client) API, the global Steam pipe is used, which does use the one created by the running Steam client, and thus all of the messages do go through the steamclient.dll loaded by steam.exe.

For the Steam Game Server API, it calls ISteamClient::CreateLocalUser internally to create a new, separate user and pipe. Since it's not going out to the existing one, it stays local to the process, using the steamclient.dll that Dota has loaded.

I still can't reproduce your issue.

**Comment by alainhb2000** [comment] 2017-02-16 01:38
Ok, i will test again, and see wait it does.

**Comment by alainhb2000** [comment] 2017-02-16 01:42
Look:
![sin titulo](https://cloud.githubusercontent.com/assets/16402933/23003526/4f369738-f3bf-11e6-8205-408078a8d27c.png)

**Comment by psychonic** [comment] 2017-02-16 01:43
I did get that Injection timed out message on one of them, but nethook was still running fine in the background, and continued to be fine after clicking the OK / Aceptar button.

**Comment by alainhb2000** [comment] 2017-02-16 01:44
yes, this time, i didn't accepted the dialog too fast, waited the detoured messages, and it worked.
But if you accept, before detoured messages apear, dota crashes.

**Comment by psychonic** [comment] 2017-02-16 01:45
Ah, that could explain it. I definitely did not close it quickly. I did not even notice it until I was done testing and about the close the spawned console windows.

**Comment by alainhb2000** [comment] 2017-02-16 01:47
any solution to the timeout ??

**Comment by psychonic** [comment] 2017-02-16 01:51
No, but it sounds like it should be fine to just ignore it and not close it too quickly. It doesn't even get it the way of the console - it's not modal.

**Comment by alainhb2000** [comment] 2017-02-16 01:53
got it working, 
![sin titulo](https://cloud.githubusercontent.com/assets/16402933/23003744/c237a938-f3c0-11e6-9650-05b14b431a05.png)

**Comment by alainhb2000** [comment] 2017-02-16 01:59
jajjaa, yes. I can ignore the timeout. Thanks.
There's any possibility that you share a new version of your mod dll, for testing with dedicated servers?

**Comment by psychonic** [comment] 2017-02-16 02:04
If you just need Metamod (to stop the dedicated server from exiting at map load on Windows), the S2 branch of it and the dota branch of the hl2sdk repo are up to date.

I uploaded a current version of the two binaries for it here, http://users.alliedmods.net/~psychonic/s2dota/

However, a better place for support for that are the AlliedModders forums.

**Closed** 2017-02-16 02:05 UTC

**Comment by alainhb2000** [comment] 2017-02-16 02:18
Thank you very much.

**Comment by psychonic** [comment] 2017-02-16 02:25
After doubling the timeout from 5s to 10s, I can no longer reproduce the error popping up. I think it really can just take that long to fully attach.

**Comment by alainhb2000** [comment] 2017-02-16 02:44
Ohh, thanks again, 
And thanks for your time.

**Comment by alainhb2000** [comment] 2017-03-12 01:19
Thanks for the files, got the dedicated working with my emulator.
But, some times dota crashes starting or falls on a loop, some times crashes when i close it. Maybe it is because i'm hooking dota process too.
This tests was patching the same dota from steam folder, and starting the dedicated server when i launch a lobby hosted on any zone different of local.

**Comment by alainhb2000** [comment] 2017-03-12 01:20
theres any form, or any way to force dedicated server connection to use tcp instead udp ???

**Comment by Netshroud** [comment] 2017-03-12 01:20
I think there used to be a `-tcp` command-line. No idea if it's still around or which games it's in.

**Comment by alainhb2000** [comment] 2017-03-12 01:21
No that doesn't worked for me. I've already tested.
