### ISSUE TITLE
[Bug]: Can't complete login

### ISSUE THREAD

**Issue by Adios22** [SteamRE/SteamKit#1197] opened 2023-03-10 20:48 UTC
### What did you expect to happen?

SteamUser.LoginKeyCallback does not received after login beginning (LogOn((logOnDetails))) and authentication cannot be completed. Till march 6 it was working fine.

### Instead of that, what actually happened?

Can't complete login

### Which operating system are you running on?

Windows

### Which .NET Runtime are you running on?

.NET Framework

### Version

3.5

**Comment by jacobs100500** [comment] 2023-03-11 18:49
Same problem. I use WEB API authentication (ISteamUserAuth/AuthenticateUser) after receiving SteamUser.LoggedOnCallback. Session id can be taken from SteamClient.SessionID

**Comment by xPaw** [comment] 2023-03-21 08:38
Gonna close this as a duplicate of #1125. You can still login, just that `LoginKeyCallback` is not triggered.

**Closed by xPaw** 2023-03-21 08:38 UTC
Labels: bug
