### ISSUE TITLE
Have somebody tested the library in a UWP application?

### ISSUE THREAD

**Issue by Lersubem** [SteamRE/SteamKit#534] opened 2018-04-07 13:57 UTC
It's never working for me because a UWP can not access windows registery since all UWP apps are sandboxed.

**Comment by yaakov-h** [comment] 2018-04-07 14:52
Duplicate of #489.

**Comment by Lersubem** [comment] 2018-04-10 20:34
I still can't, so I was just asking if someone could use this library in an UWP app.

**Comment by Lersubem** [comment] 2018-05-16 16:28
I did add steamkit2 project to my project, i did debug it and the solution to the problem i had is adding a line of code in the file HardwareUtils.cs, and this should be exactly in GetProvider() part
                case PlatformID.Win32NT:
			return new DefaultInfoProvider();
i just made this case return a new default info provider since as i said UWP apps doesn't support direct access to Windows registry.

**Comment by yaakov-h** [comment] 2018-05-16 22:03
What does `AppContext.TargetFrameworkName` return in UWP?

**Comment by Lersubem** [comment] 2018-05-17 12:46
i tried to get the value in my app but each time i do i get NULL

**Comment by yaakov-h** [comment] 2019-02-05 05:12
Closing due to inactivity, and UWP having had updates since.

If this is still not possible out of the box we might have to actually handle `PlatformNotSupportedException` or similar.

**Closed by yaakov-h** 2019-02-05 05:12 UTC
Labels: question
