### ISSUE TITLE
[Bug]: Encountered 401 for depot manifest 578081 1224926623952854117. Aborting.

### ISSUE THREAD

**Issue by huddhudd** [SteamRE/SteamKit#1216] opened 2023-04-21 05:32 UTC
### What did you expect to happen?

 dotnet DepotDownloader.dll -app 578080 -depot 578081 -username huddcc2 -password [REDACTED]
Connecting to Steam3... Done!
Logging 'huddcc2' into Steam3...Lost connection to Steam. Reconnecting
 Done!
Logging 'huddcc2' into Steam3... Done!
Using Steam3 suggested CellID: 204
Got 102 licenses for account!
Got AppInfo for 578080
Using app branch: 'Public'.
Got depot key for 578081 result: OK
Processing depot 578081 -
Downloading depot manifest...Got manifest request code for 578081 1224926623952854117 result: 16311532807010240413
Encountered 401 for depot manifest 578081 1224926623952854117. Aborting.

Unable to download manifest 1224926623952854117 for depot 578081
App 578080 was not completely downloaded.
The operation was canceled.
Disconnected from Steam

### Instead of that, what actually happened?

Encountered 401 for depot manifest 578081 1224926623952854117. Aborting.

### Which operating system are you running on?

Windows

### Which .NET Runtime are you running on?

.NET Framework

### Version

6

**Comment by yaakov-h** [comment] 2023-04-21 05:50
Not a SteamKit bug, duplicate of https://github.com/SteamRE/DepotDownloader/issues/424

**Closed by yaakov-h** 2023-04-21 05:50 UTC
Labels: bug
